### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку linked_lists Поляков Семен

### ISSUE THREAD

**Issue by Semionn** [Semionn/au-linux-kernel-spring-2016#1]
https://github.com/Semionn/au-linux-kernel-spring-2016/commit/496f6dd829dcba28ecfcfe4cdee31b6132f05aa3

**Comment by eabatalov** [comment]
Perfect working with resources but strange logic in stack interface implementation.
See comments in commit.
4 out of 5 points.
